


//CodePlay is licensed under the
//
//Apache License 2.0
//A permissive license whose main conditions require preservation of 
//copyright and license notices. Contributors provide an express grant 
//of patent rights. Licensed works, modifications, and larger works 
//may be distributed under different terms and without source code.
//
//creadores
//CARLOS CERDA
//JOSE LOBOS
//SERGIO VARGAS
//JOSE MUÑOZ

package principal;
import gestionBD.GestionBD;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sergio Vargas
 */
//Clase principal de la interfaz
public class CodePlay extends javax.swing.JFrame {

    GestionBD gbd;
    int total=0, mPago=1, folio=0;
    /*  */ int idpr=0,  idpr2=0, idpr3=0, idpr4=0, idpr5=0, idpr6=0, idpr7=0, idpr8=0, idpr9=0, idpr10=0, idpr11=0, idpr12=0;//  tomaran el id del producto seleccionado para insertarlo en la tabla venta cuando se concrete la compra
           String salida, fecha,mediopago;
    public CodePlay() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);   //PARA QUE NO SE MAXIMIZE LA PANTALLA
        setTitle("CODE PLAY"); //TITULO DE VENTANA
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage());//ACA SE CAMBIA IMAGEN DE VENTANA
        gbd = new GestionBD();
        txtSeleccionado.setLineWrap(true);//COMANDO PARA SALTO DE LINEA EN JTEXTAREA
        txtSeleccionado.setWrapStyleWord(true);//COMANDO PARA NO CORTAR LAS PALABRAS CON SALTO DE LINEA EN JTEXTAREA
        configurarRB();
        
    }
    
        public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) tablaProducto.getModel();
        int a = tablaProducto.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        }
        tb.setRowCount(100);
       //resetea la tabla clientes
    }
    
    /**/private void configurarRB(){
        
      /**/  ButtonGroup so = new ButtonGroup();
        /**/so.add(RbtnEfectivo);
        /**/so.add(RbtnTarjeta);
             RbtnEfectivo.setSelected(true);
        
    }
    public void eliminarDettalleBoleta(){
        DefaultTableModel tb = (DefaultTableModel) tabDetalle.getModel();
        int a = tabDetalle.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        }
        tb.setRowCount(12);
        //cargaTicket();
        DefaultTableModel t = (DefaultTableModel) tabTotal.getModel();
        int b = tabTotal.getRowCount()-1;
        for (int i = b; i >= 0; i--) {           
        t.removeRow(t.getRowCount()-1);
        }
        t.setRowCount(1);

    }
    
   public void eliminarTotalVentas(){
        
        //cargaTicket();
        DefaultTableModel t = (DefaultTableModel) tabTotalVenta.getModel();
        int b = tabTotalVenta.getRowCount()-1;
        for (int i = b; i >= 0; i--) {           
        t.removeRow(t.getRowCount()-1);
        }
        t.setRowCount(50);

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo2 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        cbFarcry = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFifa19 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cbBattlefield = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbGodofwar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbGta = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbHorizon = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbResident = new javax.swing.JCheckBox();
        cbSpiderman = new javax.swing.JCheckBox();
        cbLastofUs = new javax.swing.JCheckBox();
        cbUncharted = new javax.swing.JCheckBox();
        cb3meses = new javax.swing.JCheckBox();
        cb12meses = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnMostrarJuegos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnHome3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSeleccionado = new javax.swing.JTextArea();
        TextFiTotal = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        RbtnEfectivo = new javax.swing.JRadioButton();
        RbtnTarjeta = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCelectronico = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        insertarFemenino = new javax.swing.JRadioButton();
        insertarMasculino = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txArticulos = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        txtRutIng = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        txtMontoIng = new javax.swing.JTextField();
        btnAcepCompra = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabTotal = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabDetalle = new javax.swing.JTable();
        btnLimpiaGC = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabTotalVenta = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtFolioIng = new javax.swing.JTextField();
        btnEliminarVenta = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel7.setBackground(new java.awt.Color(102, 255, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Juego o Membresia a Comprar"));

        cbFarcry.setText("$ 16.900");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farcry 4.JPG"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fifa 2019.JPG"))); // NOI18N

        cbFifa19.setText("$ 29.990");
        cbFifa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFifa19ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/battlefield 4.JPG"))); // NOI18N

        cbBattlefield.setText("$ 19.990");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/god of war.JPG"))); // NOI18N

        cbGodofwar.setText("$ 19.990");

        jLabel5.setText("Primera Persona");

        jLabel6.setText("Deportes");

        jLabel7.setText("Acción - Aventuras");

        jLabel8.setText("Acción - Aventuras");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gta.JPG"))); // NOI18N

        cbGta.setText("$ 18.990");

        jLabel10.setText("Acción - Aventuras");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horizon.JPG"))); // NOI18N

        jLabel12.setText("Acción - Aventuras");

        cbHorizon.setText("$ 19.990");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resident evil 4.JPG"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spiderman.JPG"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/the last of us.JPG"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uncharted 4.JPG"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/membresia 3.JPG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/membresia 12.JPG"))); // NOI18N

        cbResident.setText("$ 19.990");

        cbSpiderman.setText("$ 18.990");

        cbLastofUs.setText("$ 19.990");

        cbUncharted.setText("$ 19.990");

        cb3meses.setText("$ 17.990");

        cb12meses.setText("$ 39.990");

        jLabel19.setText("Acción - Aventura");

        jLabel20.setText("Acción - Aventura");

        jLabel21.setText("Acción - Aventura");

        jLabel22.setText("Acción - Aventura");

        jLabel23.setText("Membresia 3 Meses");

        jLabel24.setText("Membresia 12 Meses");

        btnMostrarJuegos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMostrarJuegos.setText("Agregar al Carro de Compras y Calcular valor total");
        btnMostrarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarJuegosActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionados"));

        btnHome3.setText("HOME");
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });

        txtSeleccionado.setColumns(20);
        txtSeleccionado.setRows(5);
        jScrollPane2.setViewportView(txtSeleccionado);

        jLabel29.setText("TOTAL :");

        RbtnEfectivo.setText("EFECTIVO");

        RbtnTarjeta.setText("TARJETA DE CREDITO");

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(27, 27, 27)
                                .addComponent(TextFiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RbtnEfectivo)
                                .addGap(18, 18, 18)
                                .addComponent(RbtnTarjeta)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(TextFiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbtnTarjeta)
                    .addComponent(RbtnEfectivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome3)
                    .addComponent(btnConfirmar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar Formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMostrarJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbFarcry)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(cbFifa19)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3)
                                        .addComponent(cbBattlefield)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel14)
                                                .addComponent(cbSpiderman)))
                                        .addComponent(cbResident))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel15)
                                        .addComponent(cbLastofUs)))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(cbGodofwar)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4)))
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbGta)
                                                    .addComponent(jLabel10)))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)))
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel16)
                                            .addComponent(cbUncharted))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb3meses)
                                                    .addComponent(jLabel23))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(cb12meses)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbHorizon)
                                                    .addComponent(jLabel12)))
                                            .addGap(20, 20, 20)))
                                    .addComponent(jLabel24)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFarcry)
                    .addComponent(cbFifa19)
                    .addComponent(cbBattlefield)
                    .addComponent(cbGodofwar)
                    .addComponent(cbGta)
                    .addComponent(cbHorizon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13))
                    .addComponent(jLabel16)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb3meses)
                    .addComponent(cbUncharted)
                    .addComponent(cbLastofUs)
                    .addComponent(cbSpiderman)
                    .addComponent(cbResident)
                    .addComponent(cb12meses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarJuegos)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Juegos", jPanel7);

        jPanel8.setBackground(new java.awt.Color(102, 255, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese datos de Cliente"));

        jLabel25.setText("Rut :");

        jLabel26.setText("Nombre :");

        jLabel27.setText("Apellido :");

        jLabel28.setText("Correo Electronico :");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jButton1.setText("MOSTRAR DATOS DE CLIENTES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDOS", "GENERO", "CORREO MAIL"
            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel30.setText("Genero :");

        grupo2.add(insertarFemenino);
        insertarFemenino.setText("Femenino");
        insertarFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarFemeninoActionPerformed(evt);
            }
        });

        grupo2.add(insertarMasculino);
        insertarMasculino.setText("Masculino");

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(89, 89, 89)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel30))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(insertarFemenino)
                                                .addGap(18, 18, 18)
                                                .addComponent(insertarMasculino)))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnIngresar)
                        .addGap(39, 39, 39)
                        .addComponent(btnModificar))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel25))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel26)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel27))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(insertarFemenino)
                            .addComponent(insertarMasculino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(btnEliminar))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );

        jTabbedPane2.addTab("Clientes", jPanel8);

        jPanel9.setBackground(new java.awt.Color(102, 255, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Compra"));

        txArticulos.setColumns(20);
        txArticulos.setRows(5);
        jScrollPane3.setViewportView(txArticulos);

        jLabel31.setText("Articulos seleccionados:");

        btnAcepCompra.setText("Aceptar");
        btnAcepCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepCompraActionPerformed(evt);
            }
        });

        jLabel32.setText("Rut Cliente:");

        jLabel33.setText("monto ingresado:");

        jLabel34.setText("Vuelto:");

        jLabel35.setText("Total a pagar:");

        tabTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "folio", "fecha_venta", "rut_cliente", "m. de pago", "N° de articulos", "total"
            }
        ));
        jScrollPane4.setViewportView(tabTotal);

        tabDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_producto", "nombre_producto", "precio unitario"
            }
        ));
        jScrollPane5.setViewportView(tabDetalle);

        btnLimpiaGC.setText("limpiar");
        btnLimpiaGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaGCGCActionPerformed(evt);
            }
        });

        btnCancelarCompra.setText("cancelar");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnLimpiaGC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                .addComponent(jLabel34)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRutIng)
                                            .addComponent(txtMontoIng, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addComponent(btnAcepCompra))
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarCompra))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(33, 33, 33)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRutIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarCompra)
                            .addComponent(btnAcepCompra)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(btnLimpiaGC))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gestion Compra (BOLETA)", jPanel9);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("gestion de venta"));

        tabTotalVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "folio", "fecha_venta", "rut_comprador", "medio_de_pago", "N° de articulos", "total pagado"
            }
        ));
        jScrollPane6.setViewportView(tabTotalVenta);

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("deshacer venta"));

        jLabel37.setText("n° de Folio:");

        txtFolioIng.setText("0");

        btnEliminarVenta.setText("deshacer");
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFolioIng, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnEliminarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtFolioIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarVenta))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnVerVentas.setText("visualizar ventas actuales");
        btnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnVerVentas)
                        .addGap(90, 90, 90)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Gestion venta", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //METODO PARA LIMPIAR FORMULARIO AREA DE TEXTO Y CHECK BOX
        txtSeleccionado.setText("");
        TextFiTotal.setText("");
        cbFarcry.setSelected(false);
        cbFifa19.setSelected(false);
        cbBattlefield.setSelected(false);
        cbGodofwar.setSelected(false);
        cbGta.setSelected(false);
        cbHorizon.setSelected(false);
        cbLastofUs.setSelected(false);
        cbResident.setSelected(false);
        cbSpiderman.setSelected(false);
        cbUncharted.setSelected(false);
        cb3meses.setSelected(false);
        cb12meses.setSelected(false);
        RbtnEfectivo.setSelected(true);
       
        total =0;
        mPago=1;

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMostrarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarJuegosActionPerformed
        
        
                
         salida = ""; //variable contador
        total =0;
         String nl = System.getProperty("line.separator");//SE DECLARA COMO NL STRING PARA USARLO COMO SALTO
                                                         //DE LIENA EN MENSAJE JOPTIONPANE
                                                         
        if(cbFarcry.isSelected())
        { salida = salida + "Farcry 4 $16.990" + nl;
         /**/idpr=1;
         total = total +16990;
             }
        else{
            idpr=0;}
        
        if(cbFifa19.isSelected()){
        salida = salida + "Fifa 19 $29.990" + nl;
         /**/idpr2=2;
       total = total +29990;}
        else{
            idpr2=0;}
        
        if(cbBattlefield.isSelected()){
        salida = salida + "Battlefield $19.990" + nl;
        /**/idpr3=3;
        total = total +19990;}
        else{
            idpr3=0;}
        if(cbGodofwar.isSelected()){
        
        salida = salida + "God of War $19.990" + nl;
        /**/idpr4=4;
        total = total +19990;}
        else{
            idpr4=0;}
        
        if(cbGta.isSelected()){
        /**/salida = salida + "GTA V $18.990" + nl;
        idpr5=5;
        total = total +18990;}
        else{
            idpr5=0;}
        
        if(cbHorizon.isSelected()){
        salida = salida + "Horizon Zero $19.990" + nl;
        /**/idpr6=6;
        total = total +19990;}
        else{
            idpr6=0;}
        
        if(cbResident.isSelected()){
        salida = salida + "Resident Evil 4 $19.990" + nl;
        /**/idpr7=7;
        total = total +19990;}
        else{
            idpr7=0;}
        
        if( cbSpiderman.isSelected()){
        salida = salida + "Spiderman $18.990" + nl;
        /**/idpr8=8;
        total = total +19990;}
        else{
            idpr8=0;}
        
        if(cbLastofUs.isSelected()){
        salida = salida + "The Last of US $19.990" + nl;
        /**/idpr9=9;
        total = total +18990;}
        else{
            idpr9=0;}
        
        if(cbUncharted.isSelected()){
        salida = salida + "Uncharted 4 $19.990" + nl;
        /**/idpr10=10;
        total = total +19990;}
        else{
            idpr10=0;}
        
        if(cb3meses.isSelected()){
        salida = salida + "Membresia de 3 Meses $17.990" + nl;
        /**/idpr11=11;
        total = total +17990;}else{
            idpr11=0;}
        
        if(cb12meses.isSelected()){
        salida = salida + "Membresia de 12 Meses $39.990" + nl;
        /**/idpr12=12;
        total = total +39990;}
        else{
            idpr12=0;}
        
        TextFiTotal.setText(Integer.toString(total));
        txtSeleccionado.setText(salida);
        
        

    }//GEN-LAST:event_btnMostrarJuegosActionPerformed

    private void cbFifa19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFifa19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFifa19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eliminar();
        gbd.VerDatos(tablaProducto);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String genero = " ";
        if (insertarFemenino.isSelected()) {
            genero="Femenino";                        
        }if(insertarMasculino.isSelected()){
            genero="Masculino";
        }
       
        
        int Rut = Integer.parseInt(txtRut.getText());
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String correo = txtCelectronico.getText();
         
        if (!"".equals(genero)) {
            
            gbd.insertarClientes(Rut, nombre, apellidos, genero, correo);
            
        }

        
        txtRut.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtCelectronico.setText("");
        //FIN METODO
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
        Gestiones ges = new Gestiones();//COSNTRUCTOR PARA LLAMAR A JFRAME GESTIONES
        ges.setVisible(true);//ACA HACEMOS VISIBLE EL JFRAME
        dispose();
    }//GEN-LAST:event_btnHome3ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       if(RbtnEfectivo.isSelected()){
        
        /**/mPago=1;//validara que el monto pagado por la compra en efectivo, puedaa entregar vuelto
        mediopago="efectivo";
       }
        else if(RbtnTarjeta.isSelected()){
                
            txtMontoIng.setText(Integer.toString(total));
            mPago=2;// vaidara que si la compra se efectua con tarjeta el monto debera ser equivalente al total a pagar, ya que si se paga con un monto mator no podra otorgar vuelto
            mediopago="debito";
           }
        
        if(total==0){
            JOptionPane.showMessageDialog(null, "no puede concretarse la seleccion de articulos \n "
                                      + "si no ah seleccionado alguno(s) \n"
                                      + "favor de seleccionar productos","CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null);
        }else{
            
            
            
        JOptionPane.showMessageDialog(null, "Luego de verificar Productos seleccionados, \n "
                                      + "Para continuar con venta debe completar \n"
                                      + "datos en pestaña Clientes!!","CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null); 
        /**/Calendar c;
        /**/c=Calendar.getInstance();
        /**/int d=c.get(Calendar.DATE) ,m=c.get(Calendar.MONTH)+1, a=c.get(Calendar.YEAR) ,hr=c.get(Calendar.HOUR), min=c.get(Calendar.MINUTE), sec=(Calendar.SECOND);
        txtSeleccionado.setText(salida);
        /**/txArticulos.setText(salida+"\n en fecha "+a+"-"+m+"-"+d);
        /**/ fecha= a+"-"+m+"-"+d;//guardara el año mes y dia para insertarla en la tabla ventas
         /**/folio = ((hr+min)*10)+sec; // sera el numero de folio para la venta 
       /**/ txtTotalPagar.setText(total+" $");}
        txtVuelto.setText(" ");
        eliminarDettalleBoleta();// TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnAcepCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepCompraActionPerformed
        String rutBd=txtRutIng.getText();
                 int pagado=0;
        
                    if(total>0)
                    { pagado = Integer.parseInt(txtMontoIng.getText());}
                    
                    if(pagado<total || total==0 ){
                    JOptionPane.showMessageDialog(null, "transaccion invalida.","CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null); 
       
                    } else if(mPago==2 && pagado>total){
                    
                        JOptionPane.showMessageDialog(null, "transaccion invalida por el medio de pago elegido.","CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null); 
                    
                    
                    }else if( (pagado>=total && mPago==1) || (pagado==total && mPago==2) ){ 
                        int vuelto=pagado-total;
                        txtVuelto.setText(vuelto+"$");
                    if(idpr==1){
                       gbd.insertarVenta(folio, rutBd , idpr,mediopago, fecha);
                    } 
                     if(idpr2==2){
                       gbd.insertarVenta(folio, rutBd , idpr2,mediopago, fecha);
                    }
                     if(idpr3==3){
                       gbd.insertarVenta(folio, rutBd , idpr3,mediopago, fecha);
                    }
                     if(idpr4==4){
                       gbd.insertarVenta(folio, rutBd , idpr4,mediopago, fecha);
                    }
                     if(idpr5==5){
                       gbd.insertarVenta(folio, rutBd , idpr5, mediopago, fecha);
                    }
                     if(idpr6==6){
                       gbd.insertarVenta(folio, rutBd , idpr6, mediopago, fecha);
                    }
                     if(idpr7==7){
                       gbd.insertarVenta(folio, rutBd , idpr7,mediopago, fecha);
                    }
                     if(idpr8==8){
                       gbd.insertarVenta(folio, rutBd , idpr8, mediopago, fecha);
                    }
                     if(idpr9==(9)){
                       gbd.insertarVenta(folio, rutBd , idpr9, mediopago, fecha);
                    }
                     if(idpr10==10){
                       gbd.insertarVenta(folio, rutBd , idpr10, mediopago, fecha);
                    }
                     if(idpr11==11){
                       gbd.insertarVenta(folio, rutBd , idpr11,mediopago, fecha);
                    }
                     if(idpr12==12){
                       gbd.insertarVenta(folio, rutBd , idpr12, mediopago, fecha);
                    }
                     gbd.DettalleBoleta(tabDetalle, folio);
                     gbd.Total(tabTotal, folio);
                     total=0;
                     RbtnEfectivo.setSelected(true);
                     mPago=1;
                    
                    
                    txtSeleccionado.setText("");
                    TextFiTotal.setText("");
                    cbFarcry.setSelected(false);
                    cbFifa19.setSelected(false);
                    cbBattlefield.setSelected(false);
                    cbGodofwar.setSelected(false);
                    cbGta.setSelected(false);
                    cbHorizon.setSelected(false);
                    cbLastofUs.setSelected(false);
                    cbResident.setSelected(false);
                    cbSpiderman.setSelected(false);
                    cbUncharted.setSelected(false);
                    cb3meses.setSelected(false);
                    cb12meses.setSelected(false);
                    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAcepCompraActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int Rut = Integer.parseInt(txtRut.getText());
        gbd.Eliminar(Rut);
        txtRut.setText("");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiaGCGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaGCGCActionPerformed
           if(total==0){
           txtRutIng.setText(" ");
           txtMontoIng.setText(" ");
           txtVuelto.setText(" ");
           txtTotalPagar.setText(" ");
           txArticulos.setText(" ");
           eliminarDettalleBoleta();
           RbtnEfectivo.setSelected(true);
           
           }   else{
                       JOptionPane.showMessageDialog(null, "accion funcional solo solo al realizar la compra. "
                               ,"CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null);
           }     // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiaGCGCActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
                  
        txtRutIng.setText(" ");
           txtMontoIng.setText(" ");
           txtVuelto.setText(" ");
           txtTotalPagar.setText(" ");
           txArticulos.setText(" ");
           eliminarDettalleBoleta();
            RbtnEfectivo.setSelected(true);
            
            
            total=0;         
            mPago=1;
            idpr=0;  idpr2=0; idpr3=0; idpr4=0; idpr5=0; idpr6=0; idpr7=0; idpr8=0; idpr9=0; idpr10=0; idpr11=0; idpr12=0;
            folio=0;
            
            txtSeleccionado.setText("");
                    TextFiTotal.setText("");
                    cbFarcry.setSelected(false);
                    cbFifa19.setSelected(false);
                    cbBattlefield.setSelected(false);
                    cbGodofwar.setSelected(false);
                    cbGta.setSelected(false);
                    cbHorizon.setSelected(false);
                    cbLastofUs.setSelected(false);
                    cbResident.setSelected(false);
                    cbSpiderman.setSelected(false);
                    cbUncharted.setSelected(false);
                    cb3meses.setSelected(false);
                    cb12meses.setSelected(false);
         // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
             Actualizar ventana = new Actualizar();
             ventana.setVisible(true);
                
    }//GEN-LAST:event_btnModificarActionPerformed

    private void insertarFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarFemeninoActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        // BOTON QUE ELIMINARA LA VENTA ATRAVEZ DEL FOLIO RESEÑADO EN EL TEXTFIELD
        int nfolio = Integer.parseInt(txtFolioIng.getText());
        System.out.println(nfolio);
        if(nfolio>0){
            gbd.eliminarVenta(nfolio);
        }else{
            JOptionPane.showMessageDialog(null, "opcion invalida "
                ,"CODE PLAY",JOptionPane.INFORMATION_MESSAGE,null);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
        //MOSTRAR INFO ACTUALIZADA DE LAS VENTAS REALIZADAS
        eliminarTotalVentas();
        gbd.totalVentas(tabTotalVenta);                                                                // TODO add your handling code here:
    }//GEN-LAST:event_btnVerVentasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnEfectivo;
    private javax.swing.JRadioButton RbtnTarjeta;
    private javax.swing.JTextField TextFiTotal;
    private javax.swing.JButton btnAcepCompra;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiaGC;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarJuegos;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JCheckBox cb12meses;
    private javax.swing.JCheckBox cb3meses;
    private javax.swing.JCheckBox cbBattlefield;
    private javax.swing.JCheckBox cbFarcry;
    private javax.swing.JCheckBox cbFifa19;
    private javax.swing.JCheckBox cbGodofwar;
    private javax.swing.JCheckBox cbGta;
    private javax.swing.JCheckBox cbHorizon;
    private javax.swing.JCheckBox cbLastofUs;
    private javax.swing.JCheckBox cbResident;
    private javax.swing.JCheckBox cbSpiderman;
    private javax.swing.JCheckBox cbUncharted;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JRadioButton insertarFemenino;
    private javax.swing.JRadioButton insertarMasculino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tabDetalle;
    private javax.swing.JTable tabTotal;
    private javax.swing.JTable tabTotalVenta;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextArea txArticulos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelectronico;
    private javax.swing.JTextField txtFolioIng;
    private javax.swing.JTextField txtMontoIng;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtRutIng;
    private javax.swing.JTextArea txtSeleccionado;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
