//CodePlay is licensed under the
//
//Apache License 2.0
//A permissive license whose main conditions require preservation of 
//copyright and license notices. Contributors provide an express grant 
//of patent rights. Licensed works, modifications, and larger works 
//may be distributed under different terms and without source code.
//
//creadores
//CARLOS CERDA
//JOSE LOBOS
//SERGIO VARGAS
//JOSE MUÑOZ

//SPLASH DEL PROGRAMA
package principal;
import com.sun.awt.AWTUtilities;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
/**
 *
 * @author Sergio Vargas
 */
public class Splash extends javax.swing.JFrame {

    private Timer t;
    private ActionListener al;

    public Splash() {
        al = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                if(jProgressBar1.getValue() < 100){
                    jProgressBar1.setValue(jProgressBar1.getValue()+5);
                }else{
                    t.stop();
                    MostrarVentana();
                }
                
            }
        };
        t = new Timer(100, al);
        initComponents(); 
        AWTUtilities.setWindowOpaque(this, false);
        t.start();
    }
    
    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(50, 260, 250, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logox400.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 300, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void MostrarVentana(){
        Login log = new Login();//LLAMAR A JFRAME LOGIN
        log.setLocationRelativeTo(null);
        log.setVisible(true);//ACA HACEMOS VISIBLE EL JFRAME
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
